version: '3'
services:
  mysql-svc:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: warehouse
      MYSQL_USER: warehouse
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
  warehouse-svc:
    depends_on:
      - mysql-svc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8888"




